#
# Recommend use for static configuration that does not change between environments.
#
# See also config/application.properties
#
causeway:

  applib:
    annotation:
      action:
        explicit: true
        command-publishing: all
        execution-publishing: all
      action-layout:
        css-class:
          patterns:
            delete.*:btn-danger,
            discard.*:btn-warning,
            remove.*:btn-warning
      property:
        command-publishing: all
        execution-publishing: all
      domain-object:
        editing: false
        entity-change-publishing: all
  core:
    meta-model:
      introspector:
        lock-after-full-introspection: true
      validator:
        allow-deprecated: false
        no-params-only: true
        explicit-object-type: true

    runtime-services:
      translation:
        po:
          mode: disabled

  extensions:
    secman:
      seed:
        admin:
          user-name: "secman-admin"
          password: "pass"
          role-name: "causeway-ext-secman-admin"
          namespace-permissions:
            sticky: "simple"
#            additional: ...
        regular-user:
          role-name: "causeway-ext-secman-user"
      permissions-evaluation-policy: allow_beats_veto
      user-menu-me-action-policy: hide

  viewer:
    common:
      application:
        about: Simple App
        brand-logo-signin: images/apache-causeway/logo-banner-591x120.png
        brand-logo-header: images/apache-causeway/logo-65x48.png
        favicon-url: images/favicon.png
        menubars-layout-file: menubars.layout.xml
        name: Simple App
        # https://stackoverflow.com/a/38983935/56880
        version: @project.version@
      credit:
        - url:  https://causeway.apache.org
          image: images/apache-causeway/logo-65x48.png
          name: Apache Causeway
    wicket:
      css: css/application.css
      js: scripts/application.js

      bookmarked-pages:
        show-chooser: true
        show-drop-down-on-footer: true

      max-title-length-in-standalone-tables: 0
      max-title-length-in-parented-tables: 0

      themes:
        show-chooser: true

      table:
        decoration:
          data-tables-net:
            options: "info: false, pagingType: 'numbers'"

  testing:
    fixtures:
      fixture-scripts-specification:
        context-class: domainapp.webapp.application.fixture.scenarios.DomainAppDemo
        run-script-default: domainapp.webapp.application.fixture.scenarios.DomainAppDemo
        recreate: domainapp.webapp.application.fixture.scenarios.DomainAppDemo
        non-persisted-objects-strategy: persist
        multiple-execution-strategy: execute

# note that properties under 'datanucleus' must use camelCase rather than kebab-case
datanucleus:
  schema:
    validateTables: true
    validateConstraints: true

  persistenceByReachabilityAtCommit: false
  identifier:
    case: MixedCase

  cache:
    level2:
      type: none
      mode: ENABLE_SELECTIVE

resteasy:
  jaxrs:
    app:
      registration: beans
    defaultPath: "/restful"

server:
  max-http-header-size: 16KB

spring:
  banner:
    location: banner.txt

  quartz:
    job-store-type: memory

management:
  endpoint:
    health:
      enabled: true

