#
# Recommend use for static configuration that does not change between environments.
#
# See also config/application.properties
#
causeway:

  applib:
    annotation:
      action:
        command-publishing: all
        execution-publishing: all
      action-layout:
        css-class:
          patterns:
            delete.*:btn-danger,
            discard.*:btn-warning,
            remove.*:btn-warning
      property:
        command-publishing: all
        execution-publishing: all
      domain-object:
        editing: false
        entity-change-publishing: all
  core:
    meta-model:
      introspector:
        lock-after-full-introspection: true
        mode: full
      validator:
        allow-deprecated: false

    runtime-services:
      translation:
        po:
          mode: disabled

  extensions:
    secman:
      seed:
        admin:
          user-name: "secman-admin"
          password: "pass"
          role-name: "causeway-ext-secman-admin"
          namespace-permissions:
            sticky: "simple"
#            additional: ...
        regular-user:
          role-name: "causeway-ext-secman-user"
      permissions-evaluation-policy: allow_beats_veto
      user-menu-me-action-policy: hide
  viewer:
    common:
      application:
        about: Simple App
        brand-logo-signin: images/apache-causeway/logo-banner-591x120.png
        brand-logo-header: images/apache-causeway/logo-65x48.png
        favicon-url: images/favicon.png
        menubars-layout-file: menubars.layout.xml
        name: Simple App
        # https://stackoverflow.com/a/38983935/56880
        version: ^project.version^
      credit:
        - image: images/apache-causeway/logo-65x48.png
          name: Apache Causeway
          url: https://causeway.apache.org
    wicket:
      css: css/application.css
      js: scripts/application.js

      bookmarked-pages:
        show-chooser: true
        show-drop-down-on-footer: true

      max-title-length-in-standalone-tables: 0
      max-title-length-in-parented-tables: 0

      themes:
        show-chooser: true
        initial: Flatly
        enabled:
          - Cerulean
          - Cosmo
          - Cyborg
          - Darkly
          - Flatly
          - Journal
          - Lumen
          - Sandstone
          - Simplex
          - Slate
          - Spacelab
          - Superhero
          - United
          - Yeti

      table:
        decoration:
          data-tables-net:
            options: "info: false, pagingType: 'numbers'"
    graphql:
      api-variant: query_with_mutations_non_spec_compliant
      authentication:
        fallback:
          username: sven
          roles:
            - simple-superuser
            - foo
            - bar

  testing:
    fixtures:
      fixture-scripts-specification:
        context-class: domainapp.webapp.application.fixture.scenarios.DomainAppDemo
        run-script-default: domainapp.webapp.application.fixture.scenarios.DomainAppDemo
        recreate: domainapp.webapp.application.fixture.scenarios.DomainAppDemo
        non-persisted-objects-strategy: persist
        multiple-execution-strategy: execute
  value-types:
    big-decimal:
      allow-grouping-separator-when-parse: false

eclipselink:
  # if enabled, then must be run with JVM arg:
  # -javaagent:lib/spring-instrument-5.3.8.jar
  weaving: false
  # if weaving subproperties are required, then specify all eclipselink.weaving
  # properties using application.properties instead (it's not possible to
  # specify both eclipselink.weaving property and its subproperties using yaml syntax)

resteasy:
  jaxrs:
    app:
      registration: beans
    defaultPath: "/restful"

server:
  max-http-header-size: 16KB

spring:
  banner:
    location: banner.txt
  quartz:
    job-store-type: memory
  graphql:
    graphiql:
      enabled: true
      path: "/graphiql"
    schema:
      printer:
        enabled: true

management:
  endpoint:
    auditevents:
      enabled: false
    beans:
      enabled: false
    caches:
      enabled: false
    configprops:
      enabled: false
    conditions:
      enabled: false
    env:
      enabled: false
    flyway:
      enabled: false
    heapdump:
      enabled: false
    health:
      enabled: true
      probes:
        enabled: false
    httptrace:
      enabled: false
    info:
      enabled: false
    integrationgraph:
      enabled: false
    jolokia:
      enabled: false
    liquibase:
      enabled: false
    logfile:
      enabled: false
    loggers:
      enabled: false
    metrics:
      enabled: false
    prometheus:
      enabled: false
    quartz:
      enabled: false
    sessions:
      enabled: false
    shutdown:
      enabled: false
    startup:
      enabled: false
    scheduledtasks:
      enabled: false
    threaddump:
      enabled: false
  endpoints:
    web:
      exposure:
        include:
          - health
      discovery:
        enabled: false
